services:
  - type: web
    name: projet-plate
    runtime: python
    plan: free
    branch: main
    buildCommand: bash build.sh
    startCommand: gunicorn core.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.11
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "1"
