# Generated by Django 5.0.1 on 2026-07-20 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('designer', 'Designer'), ('developer', 'Développeur'), ('project_manager', 'Chef de projet'), ('marketing', 'Marketing'), ('content_writer', 'Rédacteur'), ('account_manager', 'Account Manager'), ('other', 'Autre')], max_length=50, verbose_name='Poste')),
                ('hire_date', models.DateField(verbose_name="Date d'embauche")),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('on_leave', 'En congé')], default='active', max_length=20, verbose_name='Statut')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Département')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['-hire_date'],
            },
        ),
    ]
