# Generated by Django 5.0.1 on 2026-09-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisummary',
            name='reference_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date concernée'),
        ),
    ]
