# Generated by Django 5.0.1 on 2026-07-20 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('permission', 'Permission'), ('leave', 'Congé'), ('absence', 'Absence')], max_length=20, verbose_name='Type')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('reason', models.TextField(verbose_name='Motif')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Refusé')], default='pending', max_length=20, verbose_name='Statut')),
                ('admin_comment', models.TextField(blank=True, verbose_name='Commentaire administrateur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to='employees.employee', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Demande de permission',
                'verbose_name_plural': 'Demandes de permission',
                'ordering': ['-created_at'],
            },
        ),
    ]
