# Generated by Django 5.0.1 on 2026-08-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionrequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='permission_attachments/', verbose_name='Justificatif'),
        ),
        migrations.AddField(
            model_name='permissionrequest',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de décision'),
        ),
        migrations.AddField(
            model_name='permissionrequest',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='permissionrequest',
            name='reason_choice',
            field=models.CharField(blank=True, choices=[('medical', 'Rendez-vous médical'), ('vacation', 'Vacances'), ('family', 'Raison familiale'), ('personal', 'Raison personnelle'), ('training', 'Formation'), ('other', 'Autre')], max_length=20, verbose_name='Motif'),
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Refusée'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='type',
            field=models.CharField(choices=[('permission', 'Permission'), ('annual', 'Congé annuel'), ('sick', 'Congé maladie'), ('unpaid', 'Congé sans solde'), ('absence', 'Absence')], max_length=20, verbose_name='Type de demande'),
        ),
    ]
