# Generated by Django 5.0.1 on 2026-07-20 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('content', models.TextField(verbose_name='Contenu du rapport')),
                ('tasks_completed', models.TextField(blank=True, verbose_name='Tâches terminées')),
                ('tasks_in_progress', models.TextField(blank=True, verbose_name='Tâches en cours')),
                ('ai_generated', models.BooleanField(default=True, verbose_name='Généré par IA')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to=settings.AUTH_USER_MODEL, verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Rapport quotidien',
                'verbose_name_plural': 'Rapports quotidiens',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
