# Generated by Django 5.0.1 on 2026-09-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='planned_date',
            field=models.DateField(blank=True, help_text='Journée de la todo list à laquelle cette activité est rattachée.', null=True, verbose_name='Jour prévu'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'À faire'), ('in_progress', 'En cours'), ('review', 'En révision'), ('completed', 'Terminé'), ('not_done', 'Non réalisée'), ('cancelled', 'Annulé')], default='todo', max_length=20, verbose_name='Statut'),
        ),
    ]
