# Generated by Django 5.0.1 on 2026-09-22 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('tasks', '0003_task_planned_date_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='block_title',
            field=models.CharField(blank=True, help_text='Titre du groupe affiché sur le plan de travail, par exemple « Analyse du site actuel ».', max_length=120, verbose_name='Bloc du plan'),
        ),
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('objective', models.CharField(blank=True, max_length=220, verbose_name='Objectif du jour')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to='employees.employee', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Plan du jour',
                'verbose_name_plural': 'Plans du jour',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
